#! /bin/sh
#
# Example panel for LemonBoy's bar

source ~/.config/lemonbar/panel.cfg

num_mon=$(bspc query -M | wc -l)

get_desktop_layout () {
    layout=$1

    if [ "$layout" = "T" ]; then
        layout="%{A:bspc desktop --layout monocle:}%{A}"
    elif [ "$layout" = "M" ]; then
        layout="%{A:bspc desktop --layout tiled:}%{A}"
    else
        layout="$layout"
    fi

    printf "%s\n" "${layout}"
}

while read -r line ; do
    case $line in
        C*)
            # Clock output
            the_time="${line#?}"
            ;;
        w*)
            # WiFi output
            wifi="${line#?}"
            ;;
        V*)
            # Volume output
            vol="${line#?}"
            ;;
        B*)
            # clock output
            battery_status="${line#?}"
            ;;
        T*)
            # xtitle output
            title="${line#?}"
            ;;
        Z*)
            long_sleep="${line#?}"
            ;;
        M*)
            music_control="${line#?}"
            ;;
        W*)
            # bspwm internal state
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    M*)
                        # active monitor
                        if [ $num_mon -gt 1 ] ; then
                            wm_infos="${wm_infos}%{F$ACTIVE_MONITOR_FG}%{B$ACTIVE_MONITOR_BG} ${name} %{B-}%{F-}"
                        else
                            wm_infos="${wm_infos}%{B#FF${BOLD_BLACK}}%{F#FF${WHITE}} ${name} %{F-}%{B-}"
                        fi
                        ;;
                    m*)
                        # inactive monitor
                        if [ $num_mon -gt 1 ] ; then
                            wm_infos="${wm_infos}%{F$INACTIVE_MONITOR_FG}%{B$INACTIVE_MONITOR_BG} ${name} %{B-}%{F-}"
                        fi
                        ;;
                    O*)
                        # focused occupied desktop
                        wm_infos="${wm_infos}%{F$FOCUSED_OCCUPIED_FG}%{B$FOCUSED_OCCUPIED_BG}%{U$FOCUSED_OCCUPIED_UL}%{+u} %{A:bspc desktop -f ${name}:}${name}%{A} %{-u}%{B-}%{F-}"
                        ;;
                    F*)
                        # focused free desktop
                        wm_infos="${wm_infos}%{F$FOCUSED_FREE_FG}%{U$FOCUSED_FREE_UL}%{B$FOCUSED_FREE_BG}%{+u} %{A:bspc desktop -f ${name}:}${name}%{A} %{-u}%{B-}%{F-}"
                        ;;
                    U*)
                        # focused urgent desktop
                        wm_infos="${wm_infos}%{F$FOCUSED_URGENT_FG}%{B$FOCUSED_URGENT_BG}%{U$FOREGROUND}%{+u} %{A:bspc desktop -f ${name}:}${name}%{A} %{-u}%{B-}%{F-}"
                        ;;
                    o*)
                        # occupied desktop
                        wm_infos="${wm_infos}%{F$OCCUPIED_FG}%{B$OCCUPIED_BG}%{U$OCCUPIED_UL}%{+u} %{A:bspc desktop -f ${name}:}${name}%{A} %{-u}%{B-}%{F-}"
                        ;;
                    f*)
                        # free desktop
                        wm_infos="${wm_infos}%{F$FREE_FG}%{B$FREE_BG} %{A:bspc desktop -f ${name}:}${name}%{A} %{B-}%{F-}"
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="${wm_infos}%{F$URGENT_FG}%{B$URGENT_BG} %{A:bspc desktop -f ${name}:}${name}%{A} %{B-}%{F-}"
                        ;;
                    L*)
                        # layout
                        wm_infos="${wm_infos}%{B#FF${BOLD_BLACK}}%{F#FF${WHITE}} $(get_desktop_layout ${name}) %{F-}%{B-}"
                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "%{l}${wm_infos} %{c}${title} %{r}${music_control} ${long_sleep} ${wifi} ${vol} ${battery_status} ${the_time}"
done
