#! /bin/sh
#
# Example panel for LemonBoy's bar


source ~/.config/lemonbar/panel.cfg

num_mon=$(bspc query -M | wc -l)

get_desktop_layout () {
    layout=$1

    if [ "$layout" = "T" ]; then
        icon=""
    elif [ "$layout" = "M" ]; then
        icon=""
    else
        icon="$layout"
    fi

    printf "%s\n" "${icon}"
}

while read -r line ; do
    case $line in
        S*)
            # clock output
            right="${line#?}"
            ;;
        T*)
            # xtitle output
            title="${line#?}"
            ;;
        Z*)
            long_sleep="${line#?}"
            ;;
        W*)
            # bspwm internal state
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    M*)
                        # active monitor
                        if [ $num_mon -gt 1 ] ; then
                            wm_infos="${wm_infos} %{F$ACTIVE_MONITOR_FG}%{B$ACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
                        else
                            wm_infos="${wm_infos}%{B#FF${BOLD_BLACK}}%{F#FF${WHITE}} ${name} %{F-}%{B-} "
                        fi
                        ;;
                    m*)
                        # inactive monitor
                        if [ $num_mon -gt 1 ] ; then
                            wm_infos="${wm_infos} %{F$INACTIVE_MONITOR_FG}%{B$INACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
                        fi
                        ;;
                    O*)
                        # focused occupied desktop
                        wm_infos="${wm_infos}%{F$FOCUSED_OCCUPIED_FG}%{B$FOCUSED_OCCUPIED_BG}%{U$FOCUSED_OCCUPIED_UL}%{+u} ${name} %{-u}%{B-}%{F-}"
                        ;;
                    F*)
                        # focused free desktop
                        wm_infos="${wm_infos}%{F$FOCUSED_FREE_FG}%{U$FOCUSED_FREE_UL}%{B$FOCUSED_FREE_BG}%{+u} ${name} %{-u}%{B-}%{F-}"
                        ;;
                    U*)
                        # focused urgent desktop
                        wm_infos="${wm_infos}%{F$FOCUSED_URGENT_FG}%{B$FOCUSED_URGENT_BG}%{U$FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
                        ;;
                    o*)
                        # occupied desktop
                        wm_infos="${wm_infos}%{F$OCCUPIED_FG}%{B$OCCUPIED_BG}%{U$OCCUPIED_UL}%{+u} ${name} %{-u}%{B-}%{F-}"
                        ;;
                    f*)
                        # free desktop
                        wm_infos="${wm_infos}%{F$FREE_FG}%{B$FREE_BG} ${name} %{B-}%{F-}"
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="${wm_infos}%{F$URGENT_FG}%{B$URGENT_BG} ${name} %{B-}%{F-}"
                        ;;
                    L*)
                        # layout
                        wm_infos="${wm_infos}%{B#FF${BOLD_BLACK}}%{F#FF${WHITE}} $(get_desktop_layout ${name}) %{F-}%{B-}"
                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "%{l}${wm_infos} %{c}${title}  %{r}${long_sleep} ${right}"
done
