#!/bin/bash

clock() {
    clock -sf 'S%A %Y-%m-%d %H:%M:%S'
}

battery() {
    BATC=/sys/class/power_supply/BAT0/capacity
    BATS=/sys/class/power_supply/BAT0/status

    test "`cat $BATS`" = "Charging" && echo -n '+' || echo -n '-'
    cat $BATC
}

volume() {
    amixer get Master | sed -n 's/^.*\[\([0-9]\+\)%.*$/\1/p'| uniq
}

cpu() {
    ps -eo pcpu | awk 'BEGIN {sum=0.0f} {sum+=$1} END {print sum}'
}

network() {
    read lo int1 int2 <<< `ip link | sed -n 's/^[0-9]: \(.*\):.*$/\1/p'`

    # iwconfig returns an error code if the interface tested has no wireless
    # extensions
    if iwconfig $int1 >/dev/null 2>&1; then
        wifi=$int1
        eth0=$int2
    else 
        wifi=$int2
        eth0=$int1
    fi

    ip link show $eth0 | grep 'state UP' >/dev/null && INT=$eth0 || INT=$wifi

    ping -c 1 8.8.8.8 >/dev/null 2>&1 && echo "$INT connected" || echo "$INT disconnected"
}

active_desktop() {
    CUR=`xprop -root _NET_CURRENT_DESKTOP` | awk '{print $3}'
    TOT=`xprop -root _NET_NUMBER_OF_DESKTOPS` | awk '{print $3}'
    echo "$CUR/$TOT"
}

# # This loop will fill a buffer with our infos, and output it to stdout.
# # while :; do
#     BUFFER=""
#     BUFFER="${BUFFER} [$(active_desktop)]   --  "
#     BUFFER="${BUFFER} CLK: $(clock) -"
#     BUFFER="${BUFFER} NET: $(network) -"
#     BUFFER="${BUFFER} CPU: $(cpu)% -"
#     #BUFFER="${BUFFER} RAM: $(memused)%% -"
#     BUFFER="${BUFFER} VOL: $(volume)%"
#     # BUFFER="${BUFFER} MPD: $(nowplaying)"
#     BUFFER="${BUFFER} BAT: $(battery)%"

#     echo $BUFFER
#     # sleep 1
# # done
