#!/bin/sh
# end a command with ; to run in a terminal

NORMAL_BACKGROUND="#282A2E"
NORMAL_FOREGROUND="#707880"

SELECTED_BACKGROUND="#373B41"
SELECTED_FOREGROUND="#C5C8C6"

FONT="-*-terminus-medium-*-*-*-16-*-*-*-*-*-*-*"

OPTIONS="-fn $FONT -nb $NORMAL_BACKGROUND -nf $NORMAL_FOREGROUND -sb $SELECTED_BACKGROUND -sf $SELECTED_FOREGROUND -i"

DMENU="dmenu -p >> -b -i $OPTIONS"
TERMI="termite -e"
CACHE="$HOME/.dmenu_cache_recent"

touch $CACHE
MOST_USED=`sort $CACHE | uniq -c | sort -r | colrm 1 8`
RUN=`(echo "$MOST_USED"; dmenu_path | grep -vxF "$MOST_USED") | $DMENU $@` &&
(echo $RUN; head -n 99 $CACHE) > $CACHE.$$ &&
mv $CACHE.$$ $CACHE

case $RUN in
    *\;) exec `echo $TERMI $RUN | sed -e 's/;$//'`;;
    *)   exec $RUN;;
esac
