#!/bin/bash

bspc config border_width            0
bspc config window_gap              0

bspc config focus_follows_pointer   true
bspc config borderless_monocle      true
bspc config auto_cancel             true
bspc config gapless_monocle         false

bspc rule -a spotify desktop=^1 split_dir=right split_ratio=0.40
bspc rule -a HipChat desktop=^1 split_dir=left split_ratio=0.60
bspc rule -a pavucontrol floating=on
bspc rule -a arandr floating=on
# Always float Authy
bspc rule -a crx_gaedmjdfmmahhbjefcbgaolhhanlaolb floating=on

IN="eDP1"
EXT="DP2-2-8"
EXT2="DP1"

monitors=`bspc query -M | wc -l`

if [ $monitors -eq 2 ]
then
    bspc monitor $IN -n "" -d misc
    bspc monitor $EXT -n "" -d web dev
    source /home/k/.profile && panel_dual &
elif [ $monitors -eq 3 ]
then
    bspc monitor $IN -n "" -d misc
    bspc monitor $EXT -n "" -d web dev
    bspc monitor $EXT2 -n "" -d right
    source /home/k/.profile && panel_dual &
else
    bspc monitor -n "" -d misc web dev
    source /home/k/.profile && panel &
fi

bspc desktop -f web
