#!/bin/bash

# i=1
# for monitor in $(bspc query -M); do
# bspc monitor $monitor \
#         -n "$i" \
#         -d $i/{i,ii,iii,iv,v,vi,vii,viii,ix,x}
#     let i++
# done
# NMON=$i
# unset i

bspc config border_width            2
bspc config window_gap              10

bspc config split_ratio             0.40
bspc config focus_follows_pointer   true
bspc config history_aware_focus     true
# bspc config borderless_monocle  true
# bspc config gapless_monocle     true
# bspc config focus_by_distance   true


# bspc rule -a Gimp follow=on floating=on
bspc rule -a spotify desktop=^1 split_dir=right split_ratio=0.40
bspc rule -a HipChat desktop=^1 split_dir=left split_ratio=0.60
# bspc rule -a mplayer2 floating=on
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc monitor -d misc web dev 1 2 3 4

setxkbmap dk

source /home/k/.profile && panel &
