#!/bin/bash

bspc config border_width            2
bspc config window_gap              10

bspc config split_ratio             0.40
bspc config focus_follows_pointer   true
bspc config borderless_monocle      true
bspc config auto_cancel             true
bspc config gapless_monocle         false

bspc rule -a spotify desktop=^1 split_dir=right split_ratio=0.40
bspc rule -a HipChat desktop=^1 split_dir=left split_ratio=0.60
# Always float Authy
bspc rule -a crx_gaedmjdfmmahhbjefcbgaolhhanlaolb floating=on

laptop_monitor='eDP1'
monitors=`bspc query -M | wc -l`

if [ $monitors -eq 2 ]
then
    other=`bspc query -M | grep -v $laptop_monitor`

    bspc monitor $laptop_monitor -n "" -d misc
    bspc monitor $other -n "" -d web dev
    source /home/k/.profile && panel_dual &
else
    bspc monitor -n "" -d misc web dev
    source /home/k/.profile && panel &
fi

bspc desktop -f web
